# Generated by Django 5.2.8 on 2025-12-07 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_remove_profile_bio_remove_profile_tags_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="height",
            new_name="height_feet",
        ),
        migrations.AddField(
            model_name="profile",
            name="height_inches",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
