# Generated by Django 5.2.8 on 2025-12-12 02:53

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0006_tag_remove_profile_interests_alter_profile_image_and_more"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="tags",
        ),
        migrations.AddField(
            model_name="profile",
            name="tags",
            field=taggit.managers.TaggableManager(
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]