# Generated by Django 5.2.8 on 2026-06-29 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0010_email_verified"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_support",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="report",
            name="resolution_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="report",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="report",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports_resolved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("resolved", "Resolved — Action Taken"),
                    ("dismissed", "Dismissed — No Violation"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
