"""
Django settings for tagmatch project.
Generated by 'django-admin startproject' using Django 5.0.14.
"""

from pathlib import Path
import os

# ---------------------------------------------------------
# Paths
# ---------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env if present (no extra package required)
_env_path = BASE_DIR / ".env"
if _env_path.exists():
    with open(_env_path) as _f:
        for _line in _f:
            _line = _line.strip()
            if _line and not _line.startswith("#") and "=" in _line:
                _key, _, _val = _line.partition("=")
                os.environ.setdefault(_key.strip(), _val.strip())

# ---------------------------------------------------------
# Security
# ---------------------------------------------------------
SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-fallback-do-not-use-in-production")
DEBUG = os.environ.get("DEBUG", "True") == "True"
ALLOWED_HOSTS = []


# ---------------------------------------------------------
# Installed Apps
# ---------------------------------------------------------
INSTALLED_APPS = [
    # Django core
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',      # Django messages framework
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    # Third-party
    'django_filters',               # search & filtering
    'taggit',                       # tagging system
    'storages',                     # AWS S3 integration
    # Local apps
    'profiles',                     # user profiles, images, tags
    'messaging',                    # optional messaging system
    # 'matches',                    # removed — unused; tag-overlap matching lives in tagmatch/views.py
    'gallery',                      # image uploads & management
]


# ---------------------------------------------------------
# Middleware
# ---------------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# ---------------------------------------------------------
# URL + WSGI
# ---------------------------------------------------------
ROOT_URLCONF = "tagmatch.urls"
WSGI_APPLICATION = "tagmatch.wsgi.application"


# ---------------------------------------------------------
# Templates
# ---------------------------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'tagmatch' / 'templates'
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # ✅ Add your custom processor here
                'messaging.context_processors.unread_message_count',
            ],
        },
    },
]



# ---------------------------------------------------------
# Database (SQLite for development)
# ---------------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ---------------------------------------------------------
# Password Validation
# ---------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# ---------------------------------------------------------
# Internationalization
# ---------------------------------------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "EST"
USE_I18N = True
USE_TZ = True


# ---------------------------------------------------------
# Static Files
# ---------------------------------------------------------
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / "tagmatch" / "static"
]
STATIC_ROOT = BASE_DIR / "staticfiles"


# ---------------------------------------------------------
# Media Files (User Uploads)
# ---------------------------------------------------------
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "tagmatch" / "media"


# ---------------------------------------------------------
# Email Backend (Enable when ready)
# ---------------------------------------------------------
# For development (prints emails to console):
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# For real email sending (example: Gmail SMTP):
# EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
# EMAIL_HOST = "smtp.gmail.com"
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
# EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")

DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "noreply@tagmatch.com")
ADMINS = [("Admin", os.environ.get("ADMIN_EMAIL", ""))]


# ---------------------------------------------------------
# Default Primary Key
# ---------------------------------------------------------
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
