# Generated by Django 5.2.8 on 2025-12-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="receiver",
            new_name="recipient",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="timestamp",
            new_name="sent_at",
        ),
        migrations.AddField(
            model_name="message",
            name="subject",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
